### ISSUE TITLE
Linux build is broken

### ISSUE THREAD

**Issue by tlemo** [irlanrobson/bounce_softbody#1]
I noticed a couple of small issues:

1. glad_glx sources are missing
2. `sprintf_s` is a MSVC only extension

**Comment by irlanrobson** [comment]
Thanks.

**Comment by irlanrobson** [comment]
Have you tested this fix on Linux?

**Comment by tlemo** [comment]
> Have you tested this fix on Linux?

With #2, I was able to build and run the testbed on Linux (Ubuntu 18.04).

**Comment by irlanrobson** [comment]
Well, thanks again for your PR.
